version: '3.1'

services:
  sender-service:
    build: ./sender-service
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"

  sender-cli:
     build: ./sender-cli
     ports:
          - 50052:50051
     depends_on:
        - sender-service
     environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"

