version: '3.1'

services:
  sender-service:
    build: ./sender-service
    ports:
      - 50051:50051
    depends_on:
     - kafka-server1

    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      MICRO_BROKER: kafka
      MICRO_BROKER_ADDRESS: kafka-server1:9092

  sender-cli:
     build: ./sender-cli
     ports:
          - 50052:50051
     depends_on:
        - sender-service
     environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      MICRO_BROKER: kafka
      MICRO_BROKER_ADDRESS: kafka-server1:9092

  zookeeper-server:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-server1:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CREATE_TOPICS= mail.send:1:1,mail.error:1:1
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server
